/**
 * Lint rules for the design system.
 *
 * The premise is that a component library's job is to be *predictable*, so the
 * TypeScript rules here are the strict, type-aware ones rather than the
 * syntax-only defaults: `strictTypeChecked` catches the floating promise, the
 * unnecessary condition and the unsound `any` that `tsc --noEmit` is happy to
 * let through. Type-aware linting needs a TypeScript program, which is why the
 * `projectService` is on — it costs a few seconds per run and is worth it.
 *
 *   pnpm lint       # report
 *   pnpm lint:fix   # report and fix what is mechanical
 *
 * `pnpm verify` runs this before anything else, so a lint error fails the same
 * gate a type error does.
 */
import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import storybook from 'eslint-plugin-storybook'

export default tseslint.config(
  {
    // Build output and vendored artefacts. `registry/` is generated by
    // `pnpm registry` from the sources that *are* linted.
    ignores: [
      'dist/**',
      'storybook-static/**',
      'registry/**',
      'coverage/**',
      'node_modules/**',
      '.shots/**',
      // Generated page shells, written by examples/vite.config.ts. They hold
      // no JavaScript beyond a two-line import of examples/src/boot.tsx.
      'examples/*/index.html',
    ],
  },

  js.configs.recommended,

  // Type-aware linting for everything TypeScript. `strictTypeChecked` is the
  // opinionated tier; `stylisticTypeChecked` adds the consistency rules that
  // only a type checker can decide (`Array<T>` vs `T[]`, redundant type
  // arguments, `??` over `||`).
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    extends: [tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        // Resolves each file to the tsconfig that owns it, and falls back to
        // an inferred project for the config files at the repo root, which
        // tsconfig.json deliberately does not include.
        projectService: {
          allowDefaultProject: ['*.ts', '*.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The library's public surface is JSDoc'd prop interfaces; an unused
      // parameter named `_foo` is usually a deliberate signature placeholder.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // `onClick={() => setOpen(true)}` is the idiom this library is written
      // in, and it is not confusing — the shorthand body is a call, not a
      // value being returned somewhere it matters. The rule keeps its teeth
      // where they count: a `return doSomethingVoid()` in a non-void function.
      '@typescript-eslint/no-confusing-void-expression': [
        'error',
        { ignoreArrowShorthand: true },
      ],
      // Every `||` in this library is boolean logic — `disabled || loading`,
      // `{(title || actions) && …}`, `totals[i] || 1` guarding a divide — not a
      // default that meant to be `??`. Ignoring the primitive operands leaves
      // the rule pointed at the case it is actually good at: an object or
      // string-ish value falling back through `||` when only null and undefined
      // should trigger the fallback.
      '@typescript-eslint/prefer-nullish-coalescing': [
        'error',
        { ignorePrimitives: { boolean: true, number: true } },
      ],
      // Template literals over `${someNumber}` are everywhere in style and
      // class-name construction and are not a defect.
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: false, allowNullish: false },
      ],
    },
  },

  // React. The new JSX transform means neither `React` nor `react/jsx-uses-react`
  // is needed; `jsx-runtime` turns those two rules off.
  {
    files: ['**/*.{tsx,jsx}'],
    extends: [
      react.configs.flat.recommended,
      react.configs.flat['jsx-runtime'],
      jsxA11y.flatConfigs.recommended,
    ],
    settings: { react: { version: 'detect' } },
    rules: {
      // Props are typed by TypeScript interfaces, not runtime propTypes.
      'react/prop-types': 'off',
      // `<ChatMessage role="user">` is a domain prop, not an ARIA role. Only
      // check the attribute where it actually is one.
      'jsx-a11y/aria-role': ['error', { ignoreNonDOM: true }],
      // Composite widgets here put the key handler on the container and the
      // focus on the children — a tablist listening for ArrowRight, a dialog
      // layer listening for Escape. That container is not itself the control,
      // so the rule's premise does not hold. A click handler on a static div
      // still is a mistake, and is still reported.
      'jsx-a11y/no-static-element-interactions': [
        'error',
        { handlers: ['onClick', 'onMouseDown', 'onMouseUp'] },
      ],
      // A chart is `role="img"` and takes a single tab stop, with the arrow
      // keys driving a virtual cursor inside it — the accessible-chart pattern,
      // not an interactive control wearing the wrong role.
      'jsx-a11y/no-noninteractive-tabindex': ['error', { roles: ['tabpanel', 'img'] }],
    },
  },

  // Hooks rules apply to the hooks themselves as much as to components.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
  },

  // Browser code: everything shipped, plus the Storybook config.
  {
    files: ['src/**/*.{ts,tsx}', '.storybook/**/*.{ts,tsx}', 'examples/src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },

  // Stories are documentation, and their fixtures sit a few lines above the
  // code that reads them.
  {
    files: ['**/*.stories.{ts,tsx}'],
    extends: [storybook.configs['flat/recommended']],
    rules: {
      // `ARTICLES[0]!`, `key[0]!.toUpperCase()`, `getAllByRole(...)[0]!` — the
      // fixture is right there, and `getAllByRole` throws rather than returning
      // an empty list. Under `noUncheckedIndexedAccess` the alternative is a
      // guard clause in a file whose job is to show what the component looks
      // like. Library code still may not assert non-null.
      '@typescript-eslint/no-non-null-assertion': 'off',
      // `onRemove: () => {}` is a story saying "this prop is required and this
      // example is static". Supplying the no-op is the point; naming it would
      // only add an import to thirty files. Library code still may not ship an
      // empty function.
      '@typescript-eslint/no-empty-function': ['error', { allow: ['arrowFunctions'] }],
    },
  },

  // Build and check scripts: Node, plain JavaScript, no type information to
  // lint against. `disableTypeChecked` keeps the type-aware rules from firing
  // on files that have no program.
  {
    files: ['**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { ...globals.node },
      sourceType: 'module',
      ecmaVersion: 'latest',
    },
  },

  // `check-examples.mjs` drives a browser. The callbacks it hands to
  // `page.evaluate` are serialised and run *in the page*, so `document` and
  // friends really are in scope — in those functions, and only those. Node's
  // globals come from the block above and stay.
  {
    files: ['scripts/check-examples.mjs'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },

  // Config files at the repo root run in Node.
  {
    files: ['*.config.{ts,js}', 'eslint.config.js', 'examples/vite.config.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
)
