import {
  cpSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
// With the .ts extension, which Vite's native config loader requires and which
// `allowImportingTsExtensions` in tsconfig.json permits.
import { EXAMPLES, type Example } from './src/catalog.ts'

/**
 * Builds everything on the published site except the Storybook.
 *
 *   pnpm site           # dev server, same URLs as the deployed site
 *   pnpm build-pages    # into site-dist/
 *   pnpm build-site     # this, then the Storybook into site-dist/storybook/
 *
 * The layout it produces:
 *
 *   /                    the landing page — where to go, and why
 *   /examples/           the index of sample applications
 *   /examples/<slug>/    one whole application per directory
 *   /r/*.json            the shadcn registry, copied in below
 *   /storybook/          added afterwards by `pnpm build-storybook`
 *
 * Everything is relative — `base` included — so the same build works at a
 * user-site root, at a project site's subpath, and from a file:// directory.
 *
 * There is no second copy of any component here. These pages import
 * `src/index.ts` and `src/stories/*.stories.tsx` directly; if a story changes,
 * the example changes with it, and if a story breaks, this build fails. That is
 * the only arrangement worth having — a set of demos maintained separately from
 * the system they demonstrate goes stale in a fortnight.
 */

const here = dirname(fileURLToPath(import.meta.url))

/** Where the generated page directories go, under the Vite root. */
const PAGES_DIR = resolve(here, 'examples')

/**
 * Marks a directory as ours to delete. Generated pages are gitignored, so a
 * renamed slug would otherwise leave its old directory behind forever — and be
 * published, since the build only overwrites what it writes.
 */
const GENERATED = '<!-- Generated by site/vite.config.ts. Do not edit. -->'

const escape = (value: string) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

/**
 * Paints the stored theme before the first frame.
 *
 * `ThemeProvider` restores the choice in an effect, which is one frame too
 * late; without this, a reader who picked dark gets a white flash on every
 * navigation. A stored `system` writes nothing on purpose — the *absence* of
 * the attribute is what leaves the media query in charge.
 */
const THEME_SCRIPT = `<script>
      try {
        var t = localStorage.getItem('cds-site-theme')
        if (t === 'light' || t === 'dark') document.documentElement.setAttribute('data-cds-theme', t)
      } catch (e) {
        /* Storage disabled. The default theme is a fine outcome. */
      }
    </script>`

/**
 * One page.
 *
 * The module script is inline and says only which example this is; the work is
 * in `src/boot.tsx`, which every page shares. So a page carries no logic that
 * could drift from its neighbours, and adding an example never means writing
 * one of these by hand.
 */
function pageHtml(example: Example): string {
  return `<!doctype html>
${GENERATED}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escape(example.title)} — Clean Design System</title>
    <meta name="description" content="${escape(example.summary)}" />
    <link rel="icon" href="../../favicon.svg" />
    ${THEME_SCRIPT}
    <script type="module">
      import { mount } from '/src/boot.tsx'
      void mount(${JSON.stringify(example.slug)})
    </script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`
}

/** Removes page directories for slugs the catalog no longer has. */
function pruneStalePages(keep: Set<string>): void {
  for (const entry of readdirSync(PAGES_DIR)) {
    if (keep.has(entry)) continue
    const page = resolve(PAGES_DIR, entry, 'index.html')
    try {
      if (!statSync(page).isFile()) continue
      if (!readFileSync(page, 'utf8').includes(GENERATED)) continue
    } catch {
      continue
    }
    rmSync(resolve(PAGES_DIR, entry), { recursive: true, force: true })
  }
}

/**
 * Writes every example page and returns the Rollup inputs.
 *
 * This runs while the config is being evaluated rather than from a plugin hook,
 * because `rollupOptions.input` has to name files that already exist. It is
 * cheap — nineteen small files — and it means the dev server and the build
 * serve the identical set of URLs.
 */
function buildPages(): Record<string, string> {
  const input: Record<string, string> = {
    index: resolve(here, 'index.html'),
    examples: resolve(PAGES_DIR, 'index.html'),
  }
  for (const example of EXAMPLES) {
    const dir = resolve(PAGES_DIR, example.slug)
    mkdirSync(dir, { recursive: true })
    writeFileSync(resolve(dir, 'index.html'), pageHtml(example))
    input[example.slug] = resolve(dir, 'index.html')
  }
  pruneStalePages(new Set([...EXAMPLES.map(e => e.slug), 'index.html']))
  return input
}

/**
 * Copies the generated shadcn registry to the root of the built site.
 *
 * It has to be the root and nowhere else. `npx shadcn add
 * https://gitu.github.io/clean-design-system/r/button.json` is a public
 * contract — it is in the README, in `llms.txt`, and in whatever `components.json`
 * anyone has already written — and moving the Storybook into `/storybook/`
 * would have taken the registry with it, because it used to ride along as one
 * of Storybook's `staticDirs`. This is what unties the two.
 *
 * `writeBundle` rather than `closeBundle`: it runs once the output directory
 * exists and has been written, which is exactly when there is somewhere to copy
 * to.
 */
function registry(): Plugin {
  const from = resolve(here, '../registry')
  return {
    name: 'cds-registry',
    apply: 'build',
    writeBundle(options) {
      const to = options.dir ?? resolve(here, '../site-dist')
      try {
        statSync(from)
      } catch {
        this.error(`No registry at ${from}. Run \`pnpm registry\` first.`)
      }
      cpSync(from, to, { recursive: true })
    },
  }
}

export default defineConfig({
  root: here,
  // Relative, so nothing in the build knows or cares what path the site is
  // served from. The project site lives under /clean-design-system/; a fork's
  // will not.
  base: './',
  // Just the favicon. The registry is copied by the plugin above instead,
  // because it is generated rather than checked in.
  publicDir: resolve(here, 'public'),
  plugins: [react(), registry()],
  resolve: {
    alias: {
      // See src/storybook-test.ts — keeps the interaction-testing runtime out
      // of the six pages whose stories have `play` functions.
      'storybook/test': resolve(here, 'src/storybook-test.ts'),
    },
  },
  optimizeDeps: {
    // Same reason as `.storybook/main.ts`: MapLibre computes its worker URL at
    // runtime, and the pre-bundler cannot follow it. The build-time fix is the
    // `?worker&url` import in src/stories/RouteMap.tsx.
    exclude: ['maplibre-gl'],
  },
  build: {
    outDir: resolve(here, '../site-dist'),
    // The out directory is outside the Vite root, which Vite will not empty
    // without being told to. It is ours: only ever written by this build, and
    // always before the Storybook is built into it.
    emptyOutDir: true,
    rollupOptions: { input: buildPages() },
  },
})
